# Generated by Django 3.1.1 on 2020-09-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
